"""Cross-package import gate (PS-140) for scitex-storage.

Every module listed here is imported by this package's source but
OWNED by a peer standalone. A rename or move on the other side of
that boundary is invisible to this package's unit tests and
surfaces as ModuleNotFoundError in a user's process — which is how
the `scitex_io._load_cache` rename went undetected for weeks.

Generated by `scitex-dev ecosystem install-cross-package-gate`.

generated-by: scitex-dev 0.60.2.dev27+g1d7cc9877

A GATE NOBODY CAN DATE IS A CLAIM ABOUT AN UNKNOWN PAST. This
list is a snapshot of the cross-package imports as they stood
when the stamp above was written; it does not update itself, and
a stale copy looks exactly like a current one. Measured
2026-08-16: 17 gates across the fleet carried NO stamp and named
a generator that never existed as a command -- the real writer
was a one-shot script since deleted -- so the only way to tell a
fossil from a live gate was a filesystem sweep of mtimes. The
same disease had already been found in the audit gate (68 of 70
still calling audit_all_for_package() with no path=), and the
same cure applies: say which version wrote you.

Regenerate with:

    scitex-dev ecosystem install-cross-package-gate scitex-storage --force

Do not hand-edit the list: the PS-140 auditor recomputes it from
source on every run and fails on any drift in either direction
(a missing entry OR a stale one).

Hand-written cases go BELOW the second sentinel. Everything there
is preserved byte-identically across regeneration; everything
between the sentinels is overwritten.
"""

import importlib

import pytest

# ===== AUTO-GENERATED: cross-package imports =====
CROSS_PACKAGE_IMPORTS = [
    'scitex_app',
    'scitex_app._django',
    'scitex_app._standalone',
    'scitex_app.sdk',
    'scitex_cards',
    'scitex_dev._cli._completion',
    'scitex_dev.ecosystem',
    'scitex_dev.gui_runtime',
    'scitex_dev.hosts',
    'scitex_dev.system_deps',
    'scitex_io',
    'scitex_logging',
    'scitex_ssh',
    'scitex_ui',
    'scitex_ui.branding',
]
# ===== END AUTO-GENERATED =====


@pytest.mark.parametrize("module_name", CROSS_PACKAGE_IMPORTS)
def test_cross_package_import_resolves(module_name):
    # Arrange — skip on the ROOT, and only on the ROOT. PS-140's own
    # prose: banning the skip outright "would convert a legitimate
    # absence into a hard failure — a gate that cannot PASS, in place
    # of one that cannot FAIL." A lean install where a peer
    # distribution is genuinely absent must SKIP here, not fail.
    #
    # Two statements ON PURPOSE. The intermediate binding is what
    # makes the root/full-path distinction visible to a reader, which
    # is the entire point of the shape; inlining it to satisfy a
    # checker would make this file harder to read.
    root = module_name.split(".")[0]
    pytest.importorskip(root)

    # Act — a real import of the FULL dotted path. Not
    # importlib.util.find_spec, which only proves a module is
    # FINDABLE while the failures this gate exists to catch (a
    # renamed symbol re-exported through a package __init__) happen
    # at EXECUTION. And not importorskip(module_name), which skips on
    # the full path and so reports the rename as an absence.
    module = importlib.import_module(module_name)

    # Assert
    assert module is not None
def test_compat_uses_the_real_clihelp_when_scitex_dev_is_installed():
    # Arrange — only meaningful once scitex-dev is on the path. Skip on the
    # ROOT, then hard-import the submodule, so a renamed `ecosystem` fails
    # loudly here instead of skipping green.
    pytest.importorskip("scitex_dev")
    importlib.import_module("scitex_dev.ecosystem")
    from scitex_storage._cli import _compat

    # Act
    has_spec_help = _compat.HAS_SPEC_HELP
    # Assert
    assert has_spec_help is True


def test_cli_wires_shell_completion_when_scitex_dev_is_installed():
    # Arrange — only meaningful once scitex-dev is on the path. Skip on the
    # ROOT, then hard-import the submodule, so a renamed `_cli._completion`
    # fails loudly here instead of skipping green.
    pytest.importorskip("scitex_dev")
    importlib.import_module("scitex_dev._cli._completion")
    from scitex_storage._cli import main

    # Act
    has_completion_cmd = "print-shell-completion" in main.commands
    # Assert
    assert has_completion_cmd is True


def test_archive_module_resolves_sync_dir_from_scitex_ssh():
    # Arrange -- a hard dependency, so this should always resolve.
    from scitex_storage._transfer import _archive

    # Act
    # Assert
    assert callable(_archive.sync_dir)


def test_app_adapter_resolves_the_real_scitex_app_config_when_installed():
    # Arrange — only meaningful once scitex-app + Django are on the path.
    # Both skips are ROOT-scoped; the `from scitex_app._django import ...`
    # below is the hard import, so a renamed submodule fails rather than
    # skipping green.
    pytest.importorskip("django")
    pytest.importorskip("scitex_app")
    from scitex_app._django import ScitexAppConfig as RealScitexAppConfig

    from scitex_storage._django._app_adapter import ScitexAppConfig

    # Act
    resolved = ScitexAppConfig
    # Assert — the adapter must re-export the REAL base class (not the
    # bare-AppConfig fallback) whenever scitex-app is actually installed.
    assert resolved is RealScitexAppConfig


def _boot_django_for_storage_gui():
    """Shared helper -- NOT a test, does not itself need AAA markers."""
    import os

    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "scitex_storage._django.settings")
    import django

    django.setup()


def test_storage_config_app_defaults_true_when_django_is_installed():
    # Arrange — boot Django against the GUI's own standalone settings.
    # Both skips are ROOT-scoped; the submodule is then hard-imported so a
    # rename fails rather than skipping green.
    pytest.importorskip("django")
    pytest.importorskip("scitex_app")
    importlib.import_module("scitex_app._django")
    _boot_django_for_storage_gui()
    from django.apps import apps

    # Act
    cfg = apps.get_app_config("scitex_storage_django")

    # Assert — the collision-avoidance contract hub relies on (see apps.py).
    assert cfg.default is True


def test_storage_config_app_slug_matches_manifest_when_django_is_installed():
    # Arrange — boot Django against the GUI's own standalone settings.
    # Both skips are ROOT-scoped; the submodule is then hard-imported so a
    # rename fails rather than skipping green.
    pytest.importorskip("django")
    pytest.importorskip("scitex_app")
    importlib.import_module("scitex_app._django")
    _boot_django_for_storage_gui()
    from django.apps import apps

    # Act
    cfg = apps.get_app_config("scitex_storage_django")

    # Assert
    assert cfg.app_slug == "storage"



# EOF
