"""Unit tests for extract_text (PDF text via scitex_io.load, mode="text").

NO MOCKS (PA-306): a REAL searchable PDF is generated by the ``searchable_pdf``
fixture and read back through ``scitex_io.load(pdf, mode="text", ocr=...)`` --
the actual production path (storage dogfoods scitex-io, which owns PDF
reading). ONE assertion per test (PA-307), AAA-structured. The image-only +
OCR case is a real end-to-end test GATED on scitex-cv/easyocr being importable
(it skips in the CI sandbox, by design -- OCR is an optional extra).
"""

import pytest

from scitex_storage._document_pipeline._extract import extract_text

# The image-only OCR case needs the OPTIONAL OCR stack (scitex-cv + easyocr,
# plus PIL to synthesise a rasterised-text PDF). Resolve availability ONCE at
# import so the test body stays a single assertion (PA-307); it skips wherever
# the stack is absent (the CI sandbox, by design).
try:
    import easyocr  # noqa: F401
    import scitex_cv

    from PIL import Image, ImageDraw

    _OCR_STACK = hasattr(scitex_cv, "ocr")
except Exception:  # pragma: no cover - depends on optional extras
    _OCR_STACK = False


def test_extract_text_reads_a_line(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["INVOICE No. 4412"])
    # Act
    text = extract_text(pdf)
    # Assert
    assert "INVOICE No. 4412" in text


def test_extract_text_reads_all_lines(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["First line", "Second line"])
    # Act
    text = extract_text(pdf)
    # Assert
    assert "Second line" in text


def test_extract_text_returns_str(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["hello"])
    # Act
    text = extract_text(pdf)
    # Assert
    assert isinstance(text, str)


def test_extract_text_text_layer_needs_no_ocr(tmp_path, searchable_pdf):
    # Arrange -- a PDF WITH an embedded text layer reads with ocr disabled.
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["RECEIPT 2026"])
    # Act
    text = extract_text(pdf, ocr=False)
    # Assert
    assert "RECEIPT 2026" in text


def test_extract_text_blank_page_is_empty(tmp_path, searchable_pdf):
    # Arrange -- no text layer, OCR disabled -> empty (classifier routes misc).
    pdf = searchable_pdf(tmp_path / "blank.pdf", [])
    # Act
    text = extract_text(pdf, ocr=False)
    # Assert
    assert text == ""


def test_extract_text_missing_file_raises(tmp_path):
    # Arrange
    missing = tmp_path / "nope.pdf"
    # Act
    # Assert
    with pytest.raises(FileNotFoundError):
        extract_text(missing)


def test_extract_text_accepts_str_path(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["path as string"])
    # Act
    text = extract_text(str(pdf))
    # Assert
    assert "path as string" in text


@pytest.mark.skipif(
    not _OCR_STACK, reason="scitex-cv/easyocr OCR stack not importable"
)
def test_extract_text_ocr_reads_image_only_scan(tmp_path):
    # Arrange -- a real image-only PDF (rasterised text, NO embedded text
    # layer): the text-layer read returns empty, so ocr=True must fall through
    # to scitex-cv's OCR pass.
    img = Image.new("RGB", (600, 200), "white")
    ImageDraw.Draw(img).text((20, 80), "INVOICE 2026", fill="black")
    pdf = tmp_path / "scan.pdf"
    img.save(pdf, "PDF")
    # Act
    text = extract_text(pdf, ocr=True)
    # Assert
    assert text != ""
