"""Unit tests for extract_text (embedded PDF text-layer read).

NO MOCKS (PA-306): a REAL searchable PDF is generated by the ``searchable_pdf``
fixture and read back through pypdf -- the actual production path. ONE
assertion per test (PA-307), AAA-structured.
"""

import pytest

from scitex_storage._document_pipeline._extract import extract_text


def test_extract_text_reads_a_line(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["INVOICE No. 4412"])
    # Act
    text = extract_text(pdf)
    # Assert
    assert "INVOICE No. 4412" in text


def test_extract_text_reads_all_lines(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["First line", "Second line"])
    # Act
    text = extract_text(pdf)
    # Assert
    assert "Second line" in text


def test_extract_text_returns_str(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["hello"])
    # Act
    text = extract_text(pdf)
    # Assert
    assert isinstance(text, str)


def test_extract_text_blank_page_is_empty(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "blank.pdf", [])
    # Act
    text = extract_text(pdf)
    # Assert
    assert text == ""


def test_extract_text_missing_file_raises(tmp_path):
    # Arrange
    missing = tmp_path / "nope.pdf"
    # Act
    # Assert
    with pytest.raises(FileNotFoundError):
        extract_text(missing)


def test_extract_text_accepts_str_path(tmp_path, searchable_pdf):
    # Arrange
    pdf = searchable_pdf(tmp_path / "doc.pdf", ["path as string"])
    # Act
    text = extract_text(str(pdf))
    # Assert
    assert "path as string" in text
